from marshmallow import Schema, fields


class PlainItemSchema(Schema):
    id = fields.Int(dump_only=True)  # The id field is defined as an integer field that is marked as dump_only. This means that when serializing an Item object to JSON, the id field will be included in the output, but when deserializing JSON data into an Item object, the id field will be ignored. This is useful for fields that are generated by the database and should not be provided by the client.
    name = fields.Str(required=True)  # The name field is defined as a string field that is required. This means that when deserializing JSON data into an Item object, the name field must be present and cannot be null or empty. If the name field is missing or invalid, a validation error will be raised.
    price = fields.Float(required=True)  # The price field is defined as a float field that is required. Similar to the name field, this means that when deserializing JSON data into an Item object, the price field must be present and cannot be null or empty. If the price field is missing or invalid, a validation error will be raised.
    # store_id = fields.Int(required=True)  # The store_id field is defined as an integer field that is required. This means that when deserializing JSON data into an Item object, the store_id field must be present and cannot be null or empty. If the store_id field is missing or invalid, a validation error will be raised. This field is used to associate the item with a specific store in the database.


class PlainStoreSchema(Schema):
    id = fields.Int(dump_only=True)  # The id field is defined as an integer field that is marked as dump_only. This means that when serializing a Store object to JSON, the id field will be included in the output, but when deserializing JSON data into a Store object, the id field will be ignored. This is useful for fields that are generated by the database and should not be provided by the client.
    name = fields.Str(required=True)  # The name field is defined as a string field that is required. This means that when deserializing JSON data into a Store object, the name field must be present and cannot be null or empty. If the name field is missing or invalid, a validation error will be raised.


class PlainTagSchema(Schema):
    id = fields.Int(dump_only=True)  # The id field is defined as an integer field that is marked as dump_only. This means that when serializing a Tag object to JSON, the id field will be included in the output, but when deserializing JSON data into a Tag object, the id field will be ignored. This is useful for fields that are generated by the database and should not be provided by the client.
    name = fields.Str()         # The name field is defined as a string field that is not required. This means that when deserializing JSON data into a Tag object, the name field can be present or absent. If the name field is present, it will be used to update the corresponding attribute of the Tag object. If it is absent, the existing value of the name attribute will remain unchanged.
    # name = fields.Str(required=True)  # The name field is defined as a string field that is required. This means that when deserializing JSON data into a Tag object, the name field must be present and cannot be null or empty. If the name field is missing or invalid, a validation error will be raised.
    # store_id = fields.Int(required=True)  # The store_id field is defined as an integer field that is required. This means that when deserializing JSON data into a Tag object, the store_id field must be present and cannot be null or empty. If the store_id field is missing or invalid, a validation error will be raised. This field is used to associate the tag with a specific store in the database.


class ItemUpdateSchema(Schema):
    name = fields.Str()  # The name field is defined as a string field that is not required. This means that when deserializing JSON data into an Item object, the name field can be present or absent. If the name field is present, it will be used to update the corresponding attribute of the Item object. If it is absent, the existing value of the name attribute will remain unchanged.
    price = fields.Float()  # The price field is defined as a float field that is not required. Similar to the name field, this means that when deserializing JSON data into an Item object, the price field can be present or absent. If the price field is present, it will be used to update the corresponding attribute of the Item object. If it is absent, the existing value of the price attribute will remain unchanged.
    store_id = fields.Int()  # The store_id field is defined as an integer field that is not required. This means that when deserializing JSON data into an Item object, the store_id field can be present or absent. If the store_id field is present, it will be used to update the corresponding attribute of the Item object. If it is absent, the existing value of the store_id attribute will remain unchanged.


class ItemSchema(PlainItemSchema):
    store_id = fields.Int(required=True, load_only=True)       # The store_id field is defined as an integer field that is required and marked as load_only. This means that when deserializing JSON data into an Item object, the store_id field must be present and cannot be null or empty. If the store_id field is missing or invalid, a validation error will be raised. However, when serializing an Item object to JSON, the store_id field will not be included in the output. This is useful for fields that are used for input validation but should not be exposed in the API response.
    store = fields.Nested(PlainStoreSchema(), dump_only=True)          # The store field is defined as a nested field that uses the PlainStoreSchema for serialization. It is marked as dump_only, which means that when serializing an Item object to JSON, the store field will be included in the output, but when deserializing JSON data into an Item object, the store field will be ignored. This allows for including the associated store information in the API response without requiring the client to provide it in the request payload.
    tags = fields.List(fields.Nested(PlainTagSchema()), dump_only=True)        # The tags field is defined as a list of nested fields that use the PlainTagSchema for serialization. It is marked as dump_only, which means that when serializing an Item object to JSON, the tags field will be included in the output, but when deserializing JSON data into an Item object, the tags field will be ignored. This allows for including the associated tags information in the API response without requiring the client to provide it in the request payload.


class StoreSchema(PlainStoreSchema):
    items = fields.List(fields.Nested(PlainItemSchema()), dump_only=True)          # The items field is defined as a list of nested fields that use the PlainItemSchema for serialization. It is marked as dump_only, which means that when serializing a Store object to JSON, the items field will be included in the output, but when deserializing JSON data into a Store object, the items field will be ignored. This allows for including the associated items information in the API response without requiring the client to provide it in the request payload.
    tags = fields.List(fields.Nested(PlainTagSchema()), dump_only=True)           # The tags field is defined as a list of nested fields that use the PlainTagSchema for serialization. It is marked as dump_only, which means that when serializing a Store object to JSON, the tags field will be included in the output, but when deserializing JSON data into a Store object, the tags field will be ignored. This allows for including the associated tags information in the API response without requiring the client to provide it in the request payload.


class TagSchema(PlainTagSchema):
    store_id = fields.Int(load_only=True)          # The store_id field is defined as an integer field that is marked as load_only. This means that when deserializing JSON data into a Tag object, the store_id field can be present and will be used to associate the tag with a specific store in the database. However, when serializing a Tag object to JSON, the store_id field will not be included in the output. This is useful for fields that are used for input validation but should not be exposed in the API response.
    store = fields.Nested(PlainStoreSchema(), dump_only=True)          # The store field is defined as a nested field that uses the PlainStoreSchema for serialization. It is marked as dump_only, which means that when serializing a Tag object to JSON, the store field will be included in the output, but when deserializing JSON data into a Tag object, the store field will be ignored. This allows for including the associated store information in the API response without requiring the client to provide it in the request payload.
    items = fields.List(fields.Nested(PlainItemSchema()), dump_only=True)          # The items field is defined as a list of nested fields that use the PlainItemSchema for serialization. It is marked as dump_only, which means that when serializing a Tag object to JSON, the items field will be included in the output, but when deserializing JSON data into a Tag object, the items field will be ignored. This allows for including the associated items information in the API response without requiring the client to provide it in the request payload.


class TagAndItemSchema(Schema):
    message = fields.Str()           # The message field is defined as a string field for providing status messages.
    item = fields.Nested(ItemSchema)           # The item field is defined as a nested field that uses the ItemSchema for serialization.
    tag = fields.Nested(TagSchema)           # The tag field is defined as a nested field that uses the TagSchema for serialization.


class UserSchema(Schema):
    id = fields.Int(dump_only=True)            # The id field is defined as an integer field that is marked as dump_only. This means that when serializing a User object to JSON, the id field will be included in the output, but when deserializing JSON data into a User object, the id field will be ignored.
    firstname = fields.Str(required=True)
    lastname = fields.Str(required=True)
    username = fields.Str(required=True)             # The username field is defined as a string field that is required for creating or updating a User object.
    password = fields.Str(required=True, load_only=True)            # The password field is defined as a string field that is required for creating or updating a User object and is marked as load_only. This means that when deserializing JSON data into a User object, the password field can be present and will be used to set the user's password in the database. However, when serializing a User object to JSON, the password field will not be included in the output. This is useful for fields that are used for input validation but should not be exposed in the API response.
    email = fields.Email(required=True)
    role = fields.Str(dump_only=True)              # The role field is defined as a string field that is marked as dump_only. This means that when serializing a User object to JSON, the role field will be included in the output, but when deserializing JSON data into a User object, the role field will be ignored. This allows for including the user's role information in the API response without requiring the client to provide it in the request payload.


class UserLoginSchema(Schema):
    username = fields.Str(required=True)
    password = fields.Str(required=True, load_only=True)