"""empty message

Revision ID: 88af001b79af
Revises: 99d9f7865a11
Create Date: 2026-08-18 23:32:06.895183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88af001b79af'
down_revision = '99d9f7865a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
    op.execute("UPDATE items SET description = 'No description provided' WHERE description IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
