"""empty message

Revision ID: a7b4e919c222
Revises: 88af001b79af
Create Date: 2026-09-27 15:41:57.534693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7b4e919c222'
down_revision = '88af001b79af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Change items.price from REAL to Float
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column(
            'price',
            existing_type=sa.REAL(),
            type_=sa.Float(precision=2),
            existing_nullable=False
        )

    # Add new columns as nullable initially
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('firstname', sa.String(length=80), nullable=True)
        )
        batch_op.add_column(
            sa.Column('lastname', sa.String(length=80), nullable=True)
        )
        batch_op.add_column(
            sa.Column('email', sa.String(length=80), nullable=True)
        )
        batch_op.add_column(
            sa.Column('role', sa.String(length=40), nullable=True)
        )

    # Populate existing users
    op.execute("""
        UPDATE users
        SET
            firstname = 'Unknown',
            lastname = 'Unknown',
            email = 'user_' || id || '@example.com',
            role = 'user'
        WHERE firstname IS NULL
           OR lastname IS NULL
           OR email IS NULL
           OR role IS NULL
    """)

    # Make the new columns NOT NULL
    # and create the unique constraint on email
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column(
            'firstname',
            existing_type=sa.String(length=80),
            nullable=False
        )

        batch_op.alter_column(
            'lastname',
            existing_type=sa.String(length=80),
            nullable=False
        )

        batch_op.alter_column(
            'email',
            existing_type=sa.String(length=80),
            nullable=False
        )

        batch_op.alter_column(
            'role',
            existing_type=sa.String(length=40),
            nullable=False
        )

        batch_op.create_unique_constraint(
            'uq_users_email',
            ['email']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(
            'uq_users_email',
            type_='unique'
        )

        batch_op.drop_column('role')
        batch_op.drop_column('email')
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column(
            'price',
            existing_type=sa.Float(precision=2),
            type_=sa.REAL(),
            existing_nullable=False
        )

    # ### end Alembic commands ###