from ..db import db

class ItemModel(db.Model):          # The ItemModel class is defined as a subclass of db.Model, which is the base class provided by SQLAlchemy for defining database models. This class represents the structure and behavior of the "items" table in the database.
    __tablename__ = "items"          # The __tablename__ attribute is set to "items", which specifies the name of the table in the database that this model corresponds to. This allows SQLAlchemy to map the model to the appropriate table when performing database operations.

    id = db.Column(db.Integer, primary_key=True)          # The id attribute is defined as a column in the database table. It is of type Integer and is marked as the primary key for the table, which means that it uniquely identifies each record in the "items" table.
    name = db.Column(db.String(80), nullable=False)          # The name attribute is defined as a column in the database table. It is of type String with a maximum length of 80 characters and is marked as not nullable, which means that it cannot be left empty when creating or updating records in the "items" table.
    description = db.Column(db.String)

    price = db.Column(db.Float(precision=2), unique=False, nullable=False)          # The price attribute is defined as a column in the database table. It is of type Float with a precision of 2 decimal places and is marked as not nullable, which means that it cannot be left empty when creating or updating records in the "items" table. This attribute represents the price of the item.

    store_id = db.Column(db.Integer, db.ForeignKey("stores.id"), unique=False, nullable=False)          # The store_id attribute is defined as a column in the database table. It is of type Integer and is marked as a foreign key that references the id column in the "stores" table. This establishes a relationship between the ItemModel and StoreModel classes, allowing each item to be associated with a specific store. The attribute is also marked as not nullable, which means that it cannot be left empty when creating or updating records in the "items" table.

    store = db.relationship("StoreModel", back_populates="items")          # The store attribute is defined as a relationship between the ItemModel and StoreModel classes. It establishes a many-to-one relationship, where each item belongs to a single store. The back_populates parameter specifies the corresponding attribute in the StoreModel class that refers back to the items, allowing for bidirectional access between items and their associated store.
    tags = db.relationship("TagModel", back_populates="items", secondary="items_tags")            # The tags attribute is defined as a relationship between the ItemModel and TagModel classes. It establishes a many-to-many relationship, where each item can be associated with multiple tags and each tag can have multiple items. The back_populates parameter specifies the corresponding attribute in the TagModel class that refers back to the items, allowing for bidirectional access between items and their associated tags. The secondary parameter specifies the name of the association table ("items_tags") that is used to establish the many-to-many relationship between items and tags.