from ..db import db

class StoreModel(db.Model):          # The StoreModel class is defined as a subclass of db.Model, which is the base class provided by SQLAlchemy for defining database models. This class represents the structure and behavior of the "stores" table in the database.
    __tablename__ = "stores"          # The __tablename__ attribute is set to "stores", which specifies the name of the table in the database that this model corresponds to. This allows SQLAlchemy to map the model to the appropriate table when performing database operations.

    id = db.Column(db.Integer, primary_key=True)          # The id attribute is defined as a column in the database table. It is of type Integer and is marked as the primary key for the table, which means that it uniquely identifies each record in the "stores" table.
    name = db.Column(db.String(80), unique=True, nullable=False)          # The name attribute is defined as a column in the database table. It is of type String with a maximum length of 80 characters, marked as unique, and not nullable. This means that each store must have a unique name and cannot be left empty when creating or updating records in the "stores" table.

    items = db.relationship("ItemModel", back_populates="store", lazy="dynamic", cascade="all, delete")          # The items attribute is defined as a relationship to the ItemModel class, which represents the "items" table in the database. It establishes a one-to-many relationship between stores and items, where each store can have multiple associated items. The back_populates parameter specifies the corresponding attribute in the ItemModel class that refers back to the store. The lazy parameter is set to "dynamic", which means that the related items will be loaded only when accessed, allowing for more efficient querying. The cascade parameter is set to "all, delete", which means that when a store is deleted, all associated items will also be deleted from the database.

    tags = db.relationship("TagModel", back_populates="store", lazy="dynamic", cascade="all, delete")          # The tags attribute is defined as a relationship to the TagModel class, which represents the "tags" table in the database. It establishes a one-to-many relationship between stores and tags, where each store can have multiple associated tags. The back_populates parameter specifies the corresponding attribute in the TagModel class that refers back to the store. The lazy parameter is set to "dynamic", which means that the related tags will be loaded only when accessed, allowing for more efficient querying. The cascade parameter is set to "all, delete", which means that when a store is deleted, all associated tags will also be deleted from the database.
    