from ..db import db

class TagModel(db.Model):          # The TagModel class is defined as a subclass of db.Model, which is the base class provided by SQLAlchemy for defining database models. This class represents the structure and behavior of the "tags" table in the database.
    __tablename__ = "tags"          # The __tablename__ attribute is set to "tags", which specifies the name of the table in the database that this model corresponds to. This allows SQLAlchemy to map the model to the appropriate table when performing database operations.

    id = db.Column(db.Integer, primary_key=True)          # The id attribute is defined as a column in the database table. It is of type Integer and is marked as the primary key for the table, which means that it uniquely identifies each record in the "tags" table.
    name = db.Column(db.String(80), unique=True, nullable=False)          # The name attribute is defined as a column in the database table. It is of type String with a maximum length of 80 characters, marked as unique, and not nullable. This means that each tag must have a unique name and cannot be left empty when creating or updating records in the "tags" table.
    store_id = db.Column(db.Integer, db.ForeignKey("stores.id"), nullable=False)          # The store_id attribute is defined as a column in the database table. It is of type Integer and is marked as a foreign key that references the id column in the "stores" table. This establishes a relationship between the TagModel and StoreModel classes, allowing each tag to be associated with a specific store. The attribute is also marked as not nullable, which means that it cannot be left empty when creating or updating records in the "tags" table.

    store = db.relationship("StoreModel", back_populates="tags")          # The store attribute is defined as a relationship between the TagModel and StoreModel classes. It establishes a many-to-one relationship, where each tag belongs to a single store. The back_populates parameter specifies the corresponding attribute in the StoreModel class that refers back to the tags, allowing for bidirectional access between tags and their associated store.
    items = db.relationship("ItemModel", back_populates="tags", secondary="items_tags")        # The items attribute is defined as a relationship between the TagModel and ItemModel classes. It establishes a many-to-many relationship, where each tag can be associated with multiple items and each item can have multiple tags. The back_populates parameter specifies the corresponding attribute in the ItemModel class that refers back to the tags, allowing for bidirectional access between tags and their associated items. The secondary parameter specifies the name of the association table ("items_tags") that is used to establish the many-to-many relationship between tags and items.